### ISSUE TITLE
헉!!

### ISSUE THREAD

**Issue by howsmyanimeprofilepicture** [1pha/nwitter#1]
이거 저도 따라해본 적 있어요 ㅋㅋ

**Comment by 1pha** [comment]
진짜 딥러닝하기도 바쁘다는걸 꺠닫고 바로접어버린 ... Firebase ...

**Comment by howsmyanimeprofilepicture** [comment]
@1pha 파이어베이스는 그냥 딱 회원관리? 이런 용도로만 쓰는 게 좋은 것 같습니다ㅠ_ㅠ.... 백엔드랑 DB 직접 구현하는 게 여러 모로 마음 편하더라고요... 애증의 파베
